lang: ruby
sudo: false
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - 2.7.2
env:
  - DB=sqlite
before_install:
  - gem install bundler
script:
  - bundle exec padrino rake ar:schema:load
  - bundle exec rspec spec
