lang: ruby
sudo: false
rvm:
  - 2.3.6
  - 2.4.5
  - 2.5.3
  - ruby-head
env:
  - DB=sqlite
before_install:
  - gem install bundler
script:
  - bundle exec padrino rake ar:schema:load
  - bundle exec rspec spec
